M48
; DRILL file KiCad 10.0.4 date 2026-07-25T22:43:44
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-25T22:43:44-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X132.21Y-90.4
T1
G00X132.21Y-97.45
M15
G01X132.21Y-97.75
M16
G05
M30
